---
{{- if .Values.secret.dockerconfigjson }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Chart.Name }}-pull-secret"
type: kubernetes.io/dockerconfigjson
data:
  ".dockerconfigjson": {{ .Values.secret.dockerconfigjson | quote }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Chart.Name }}-tls"
  labels:
    app: {{ .Chart.Name }}
  annotations:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.ingress.crt }}
  tls.key: {{ .Values.ingress.key }}
