---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.Namespace }}
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '{{ .Values.service.port }}'
spec:
  selector:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: {{ .Chart.Name }}
  ports:
  - name: {{ .Chart.Name }}
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.containerPort }}
