## Nginx Ingress
## Follow https://devopscube.com/setup-ingress-kubernetes-nginx-controller/

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-ui
  namespace: {{ .Values.Namespace }}
  annotations:
    ingressClassName: nginx
spec:
  rules:
    # Use the host you used in your kubernetes Ingress Configurations
    - host: {{ .Values.ingress.domain }}
      http:
        paths:
          - backend:
              service:
                name: prometheus-service
                port:
                  number: {{ .Values.service.port }}
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - {{ .Values.ingress.domain }}
      secretName: prometheus-secret-tls
---
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-secret-tls
  namespace: {{ .Values.Namespace }}
data:
  # USe base64 in the certs
  tls.crt: {{ .Values.ingress.crt }}
  tls.key: {{ .Values.ingress.key }}
