---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
  annotations:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
spec:
  sessionAffinity: ClientIP
  ports:
    - name: http
      port: {{ .Values.service.targetport }}
      targetPort: {{ .Values.service.targetport }}
  selector:
    app: {{ .Chart.Name }}
  type: ClusterIP
  clusterIP: None
