---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.Namespace }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
spec:
  selector:
    app: {{ .Chart.Name }}
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
