---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Chart.Name }}-cm"
data:
  DOMAIN: "{{ .Values.nifi.ingress.domain }}"
  NIFI_SECURITY_USER_SAML_IDP_METADATA_URL: "https://{{ .Values.nifi.ingress.domain }}{{ .Values.nifi.config.nifi_security_user_saml_idp_metadata_url_path }}"
  K8S_NODES: "{{ .Values.nifi.config.k8s_nodes }}"
  NIFI_JVM_TIMEZONE: "{{ .Values.nifi.config.nifi_jvm_timezone }}"
  KEYSTORE_PATH: /opt/nifi/nifi-current/keytool/all/keystore.jks
  TRUSTSTORE_PATH: /opt/nifi/nifi-current/keytool/all/truststore.jks
  NIFI_SECURITY_KEYSTORE: /opt/nifi/nifi-current/keytool/all/keystore.jks
  KEYSTORE_PASSWORD: "{{ .Values.nifi.config.keystore_password }}"
  TRUSTSTORE_PASSWORD: "{{ .Values.nifi.config.truststore_password }}"
  KEYSTORE_TYPE: "jks"
  TRUSTSTORE_TYPE: "JKS"
  NIFI_SECURITY_KEYSTORETYPE: "JKS"
  NIFI_ANALYTICS_PREDICT_ENABLED: "{{ .Values.nifi.config.nifi_analytics_predict_enabled }}"
  NIFI_CLUSTER_IS_NODE: "true"
  NIFI_CLUSTER_LOAD_BALANCE_HOST: "{{ .Chart.Name }}"
  NIFI_CLUSTER_NODE_CONNECTION_TIMEOUT: "{{ .Values.nifi.config.nifi_cluster_node_connection_timeout }}"
  NIFI_CLUSTER_NODE_READ_TIMEOUT: "{{ .Values.nifi.config.nifi_cluster_node_read_timeout }}"
  NIFI_CLUSTER_NODE_EVENT_HISTORY_SIZE: "{{ .Values.nifi.config.nifi_cluster_node_event_history_size }}"
  NIFI_CLUSTER_NODE_LOAD_BALANCE_PORT: "{{ .Values.nifi.service.cluster_lb_port }}"
  NIFI_CLUSTER_NODE_PROTOCOL_MAX_THREADS: "{{ .Values.nifi.config.nifi_cluster_node_protocol_max_threads }}"
  NIFI_CLUSTER_NODE_PROTOCOL_PORT: "{{ .Values.nifi.service.cluster_port }}"
  NIFI_CLUSTER_NODE_PROTOCOL_THREADS: "{{ .Values.nifi.config.nifi_cluster_node_protocol_threads }}"
  NIFI_CLUSTER_PROTOCOL_CONNECTION_HANDSHAKE_TIMEOUT: "{{ .Values.nifi.config.nifi_cluster_protocol_connection_handshake_timeout }}"
  NIFI_CLUSTER_PROTOCOL_HEARTBEAT_INTERVAL: "{{ .Values.nifi.config.nifi_cluster_protocol_heartbeat_interval }}"
  NIFI_CLUSTER_PROTOCOL_IS_SECURE: "{{ .Values.nifi.config.nifi_cluster_protocol_is_secure }}"
  NIFI_ELECTION_MAX_CANDIDATES: "{{ .Values.nifi.hpa.minReplicas }}" # равно количеству участников кластера
  NIFI_ELECTION_MAX_WAIT: "{{ .Values.nifi.config.nifi_election_max_wait }}"
  NIFI_JVM_HEAP_INIT: "{{ .Values.nifi.resources.nifi_jvm_heap_init }}"
  NIFI_JVM_HEAP_MAX: "{{ .Values.nifi.resources.nifi_jvm_heap_max }}"
  NIFI_SECURITY_AUTORELOAD_ENABLED: "{{ .Values.nifi.config.nifi_security_autoreload_enabled }}"
  NIFI_SECURITY_AUTORELOAD_INTERVAL: "{{ .Values.nifi.config.nifi_security_autoreload_interval }}"
  NIFI_SECURITY_NEEDCLIENTAUTH: "{{ .Values.nifi.config.nifi_security_needclientauth }}"
  NIFI_CONTENT_CLAIM_MAX_APPENDABLE_SIZE: "{{ .Values.nifi.config.nifi_content_claim_max_appendable_size }}"
  AUTH: "{{ .Values.nifi.config.auth }}"
  NIFI_SECURITY_USER_SAML_SP_ENTITY_ID: "{{ .Values.nifi.config.nifi_security_user_saml_sp_entity_id }}"
  NIFI_SECURITY_USER_SAML_GROUP_ATTRIBUTE_NAME: "{{ .Values.nifi.config.nifi_security_user_saml_group_attribute_name }}"
  NIFI_SECURITY_USER_SAML_REQUEST_SIGNING_ENABLED: "{{ .Values.nifi.config.nifi_security_user_saml_request_signing_enabled }}"
  NIFI_SECURITY_USER_SAML_WANT_ASSERTIONS_SIGNED: "{{ .Values.nifi.config.nifi_security_user_saml_want_assertions_signed }}"
  NIFI_SECURITY_USER_SAML_SIGNATURE_ALGORITHM: "{{ .Values.nifi.config.nifi_security_user_saml_signature_algorithm }}"
  NIFI_SECURITY_USER_SAML_SIGNATURE_DIGEST_ALGORITHM: "{{ .Values.nifi.config.nifi_security_user_saml_signature_digest_algorithm }}"
  NIFI_SECURITY_USER_SAML_MESSAGE_LOGGING_ENABLED: "{{ .Values.nifi.config.nifi_security_user_saml_message_logging_enabled }}"
  NIFI_SECURITY_USER_SAML_METADATA_SIGNING_ENABLED: "{{ .Values.nifi.config.nifi_security_user_saml_metadata_signing_enabled }}"
  NIFI_SECURITY_USER_SAML_AUTHENTICATION_EXPIRATION: "{{ .Values.nifi.config.nifi_security_user_saml_authentication_expiration }}"
  NIFI_SECURITY_USER_SAML_SINGLE_LOGOUT_ENABLED: "{{ .Values.nifi.config.nifi_security_user_saml_single_logout_enabled }}"
  NIFI_SECURITY_USER_SAML_HTTP_CLIENT_TRUSTSTORE_STRATEGY: "NIFI"
  NIFI_SECURITY_USER_SAML_HTTP_CLIENT_CONNECT_TIMEOUT: "{{ .Values.nifi.config.nifi_security_user_saml_http_client_connect_timeout }}"
  NIFI_SECURITY_USER_SAML_HTTP_CLIENT_READ_TIMEOUT: "{{ .Values.nifi.config.nifi_security_user_saml_http_client_read_timeout }}"
  NIFI_SERVICE_CLIENT_SECRET: "{{ .Values.nifi.config.keystore_password }}"
  INITIAL_ADMIN_IDENTITY: "{{ .Values.nifi.config.initial_admin_identity }}"
  NIFI_SENSITIVE_PROPS_KEY_PROTECTED: "{{ .Values.nifi.config.keystore_password }}"
  NIFI_SENSITIVE_PROPS_KEY: "{{ .Values.nifi.config.keystore_password }}"
  NIFI_WEB_HTTPS_PORT: "{{ .Values.nifi.service.https_port }}"
  NIFI_WEB_PROXY_HOST: "{{ .Values.nifi.ingress.domain }}"
  NIFI_ZK_CONNECT_STRING: "zookeeper:{{ .Values.zookeeper.service.zk_port }}"
  NIFI_ZOOKEEPER_CONNECT_STRING: "zookeeper:{{ .Values.zookeeper.service.zk_port }}"
