
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "nfs-pv-{{ .Chart.Name }}-data"
  annotations:
    "helm.sh/resource-policy": keep
spec:
  capacity:
    storage: {{ .Values.nifi.volumes.nfs.storage }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers={{ .Values.nifi.volumes.nfs.nfsvers }}
    - retrans=10
    - timeo=60
  nfs:
    path: {{ .Values.nifi.volumes.nfs.path }}
    server: {{ .Values.nifi.volumes.nfs.server }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "nfs-pvc-{{ .Chart.Name }}-data"
  annotations:
    "helm.sh/resource-policy": keep
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
    - ReadOnlyMany
  resources:
    requests:
      storage: {{ .Values.nifi.volumes.nfs.storage }}
