---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
  annotations:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 600
  selector:
    app: {{ .Chart.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.nifi.service.cluster_lb_port }}
      targetPort: {{ .Values.nifi.service.cluster_lb_port }}
      name: cluster-lb
    - protocol: TCP
      port: {{ .Values.nifi.service.http_port }}
      targetPort: {{ .Values.nifi.service.http_port }}
      name: http
    - protocol: TCP
      port: {{ .Values.nifi.service.https_port }}
      targetPort: {{ .Values.nifi.service.https_port }}
      name: https
    - protocol: TCP
      port: {{ .Values.nifi.service.cluster_port }}
      targetPort: {{ .Values.nifi.service.cluster_port }}
      name: cluster
    - protocol: TCP
      port: {{ .Values.nifi.service.monitoring_port }}
      targetPort: {{ .Values.nifi.service.monitoring_port }}
      name: metrics
