---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
        - name: docker-postgres-init-volume
          configMap:
            name: create-database-config
            items:
              - key: docker_postgres_init.sql
                path: docker_postgres_init.sql
        - name: create-database-volume
          configMap:
            name: create-database-config
            items:
              - key: create-db.sh
                path: create-db.sh
      containers:
        - name: postgres-container
          image: postgres:14-alpine
          command:
            - "/bin/sh"
            - "-c"
            - "cp /opt/scripts/* /tmp/ && chmod +x /tmp/create-db.sh && /tmp/create-db.sh ; sleep 99999999999"
          imagePullPolicy: IfNotPresent
          ports:
            - name: postgres
              containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - name: docker-postgres-init-volume
              subPath: docker_postgres_init.sql
              mountPath: /opt/scripts/docker_postgres_init.sql
              readOnly: false
            - name: create-database-volume
              subPath: create-db.sh
              mountPath: /opt/scripts/create-db.sh
              readOnly: false
