{{- if .Values.secret.dockerconfigjson -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-regcred
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.secret.dockerconfigjson | quote }}
{{- end -}}
