---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: zookeeper
  labels:
    app.kubernetes.io/name: zookeeper
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: zookeeper
  minReplicas: 1
  maxReplicas: 1
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 300
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 90
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90
