---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  labels:
    name: zookeeper
    app: zookeeper
  annotations:
    app.kubernetes.io/name: zookeeper
    app.kubernetes.io/part-of: nifi
spec:
  revisionHistoryLimit: 1
  serviceName: zookeeper
  podManagementPolicy: OrderedReady
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      automountServiceAccountToken: false
      enableServiceLinks: false
      setHostnameAsFQDN: true
      dnsPolicy: ClusterFirstWithHostNet
      restartPolicy: Always
      securityContext:
        runAsGroup: 1000
        runAsUser: 1000
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: zookeeper
          image: docker.io/zookeeper:3.8
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 2181
              name: zk
            - containerPort: 8080
              name: http
            - containerPort: 7070
              name: metrics
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace # Use pod namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: ZOO_SERVERS
              # value: "server.1=zookeeper-0.zookeeper.$(POD_NAMESPACE).svc.cluster.local:2888:3888;2181 server.2=zookeeper-1.zookeeper.$(POD_NAMESPACE).svc.cluster.local:2888:3888;2181 server.3=zookeeper-2.zookeeper.$(POD_NAMESPACE).svc.cluster.local:2888:3888;2181"
              value: "server.1=zookeeper-0.zookeeper.$(POD_NAMESPACE).svc.cluster.local:2888:3888;2181"
            - name: POD_INDEX
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['apps.kubernetes.io/pod-index']
          envFrom:
            - configMapRef:
                name: zookeeper-cm
                optional: false
          livenessProbe:
            exec:
              command:
                - which
                - java
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            tcpSocket:
              port: zk
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
            successThreshold: 1
          resources:
            requests:
              cpu: 200m
              memory: 500Mi
            limits:
              cpu: 200m
              memory: 500Mi
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - mountPath: /data
              name: data
              subPath: data
            - mountPath: /datalog
              name: data
              subPath: datalog
            - mountPath: /conf
              name: data
              subPath: conf
            - name: start-script
              mountPath: /apache-zookeeper-3.8.4-bin/bin/zkServer.sh
              subPath: zkServer.sh
              readOnly: false
      volumes:
        - name: data
          emptyDir:
            sizeLimit: 2Gi
        - name: start-script
          configMap:
            name: zkserver.sh
            optional: false
            defaultMode: 0755
