apiVersion: v1
kind: ConfigMap
metadata:
  name: config-mdm-deployment
data:
  GUEST_MODE: "false"
  POSTGRES_ADDRESS: "10.21.2.33:5432"
  POSTGRES_USERNAME: "postgres"
  POSTGRES_PASSWORD: "notpostgres"
  DATABASE_NAME: "universe"
  SEARCH_CLUSTER_ADDRESS: "10.21.2.33:9200"
  SEARCH_CLUSTER_NAME: "docker-cluster"
  EMAIL_ENABLED: "false"
  EMAIL_SERVER_HOST: "localhost"
  EMAIL_SERVER_PORT: "5025"
  EMAIL_USERNAME: "universe@example.com"
  EMAIL_PASSWORD: "password"
  EMAIL_FRONTEND_URL: "''"
  EMAIL_SSL_ENABLE: "true"
  EMAIL_STARTTLS_ENABLE: "false"
  JAVA_TOOL_OPTIONS: ""
  CACHE_AUTO_DETECTION_ENABLED: "true"
  CACHE_GROUP: "unidata"
  CACHE_PASSWORD: "password"
  CACHE_PORT: "5701"
  CACHE_PORT_AUTOINCREMENT: "true"
  SYSTEM_NODE_ID: ""
  CACHE_PUBLIC_ADDRESS: ""
  TZ: "MSK"
  CACHE_KUBERNETES_ENABLED: "true"
  CACHE_KUBERNETES_SERVICE_NAME: "mdm-service"
  CACHE_TCP_IP_ENABLED: "false"
  CACHE_TCP_IP_MEMBERS: ""
  CACHE_DIAGNOSTICS_ENABLED: "true"
  CACHE_SECURITY_RECOMMENDATIONS: "DEBUG"
  CACHE_JET_ENABLED: "true"
  CACHE_SOCKET_BIND_ANY: "false"
  CACHE_REST_ENABLED: "true"
  CACHE_INTEGRITY_CHECKER_ENABLED: "true"
