apiVersion: v1
kind: Service
metadata:
  name: ui-service
spec:
  type: NodePort
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 600
  ports:
    - port: 8082
      targetPort: 80
      nodePort: 30082
  selector:
    app: ui
