---
{{- if .Values.secret.dockerconfigjson }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Chart.Name }}-pull-secret"
type: kubernetes.io/dockerconfigjson
data:
  ".dockerconfigjson": {{ .Values.secret.dockerconfigjson | quote }}
{{- end }}
