---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-service"
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.frontend.forward_port }}
      targetPort: {{ .Values.frontend.container_port }}
  selector:
    app: {{ .Chart.Name }}
