## VAULT
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-database-nifi
spec:
  provider: vault
  secretObjects:
  - data:
    - key: keystore-password
      objectName: keystore-password
    secretName: keystore-password
    type: Opaque
  - data:
    - key: truststore-password
      objectName: truststore-password
    secretName: truststore-password
    type: Opaque
  parameters:
    vaultAddress: "{{ .Values.vault.address }}"
    roleName: "{{ .Values.vault.rolename }}"
    objects: |
      - objectName: "keystore-password"
        secretPath: "{{ .Values.vault.secret_path }}"
        secretKey: "keystore-password"
      - objectName: "truststore-password"
        secretPath: "{{ .Values.vault.secret_path }}"
        secretKey: "truststore-password"
