---
apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: "{{ .Chart.Name }}-tls"
  labels:
    app: {{ .Chart.Name }}
  annotations:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.nifi.ingress.crt }}
  tls.key: {{ .Values.nifi.ingress.key }}
