---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    app: zookeeper
  annotations:
    app.kubernetes.io/name: zookeeper
    app.kubernetes.io/part-of: nifi
spec:
  type: ClusterIP
  selector:
    app: zookeeper
  ports:
  - protocol: TCP
    port: {{ .Values.zookeeper.service.zk_port }}
    targetPort: {{ .Values.zookeeper.service.zk_port }}
    name: zk
  - protocol: TCP
    port: {{ .Values.zookeeper.service.http_port }}
    targetPort: {{ .Values.zookeeper.service.http_port }}
    name: web
  - protocol: TCP
    port: {{ .Values.zookeeper.service.metrics_port }}
    targetPort: {{ .Values.zookeeper.service.metrics_port }}
    name: metrics
