---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-cm
data:
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "admin"
  KC_PROXY: "edge"
  jgroups.dns.query: "keycloak"
  PROXY_ADDRESS_FORWARDING: "true"
  KC_HEALTH_ENABLED: "true"
  KC_METRICS_ENABLED: "true"
  KC_HTTP_ENABLED: "true"
  KC_HTTP_RELATIVE_PATH: "/auth"
  KC_HOSTNAME_URL: "https://your_domain/keycloak/auth"
  KC_HOSTNAME_ADMIN_URL: "https://your_domain/keycloak/auth"
  KC_DB: "postgres"
  KC_DB_URL: "jdbc:postgresql://10.21.2.33:5432/keycloak"
  KC_DB_URL_HOST: "10.21.2.33"
  KC_DB_URL_PORT: "5432"
  KC_DB_URL_DATABASE: "keycloak"
  KC_DB_USERNAME: "keycloak"
  KC_DB_PASSWORD: "keycloak"
  CACHE_OWNERS_COUNT: "3"
  CACHE_OWNERS_AUTH_SESSIONS_COUNT: "3"
  # KC_HTTPS_CERTIFICATE_FILE: "/etc/certs/tls.crt"
  # KC_HTTPS_CERTIFICATE_KEY_FILE: "/etc/certs/tls.key"
