---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}
  labels:
    name: {{ .Chart.Name }}
    app: {{ .Chart.Name }}
  annotations:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  serviceName: {{ .Chart.Name }}
  podManagementPolicy: {{ .Values.podManagementPolicy }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      automountServiceAccountToken: false
      enableServiceLinks: false
      setHostnameAsFQDN: true
      dnsPolicy: ClusterFirstWithHostNet
      restartPolicy: Always
      securityContext:
        runAsGroup: 1000
        runAsUser: 1000
        runAsNonRoot: false
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: "{{ .Values.vault.service_account }}" # Vault
      imagePullSecrets:
        - name: "{{ .Chart.Name }}-regcred"
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.http_port }}
              name: http
            - containerPort: {{ .Values.service.https_port }}
              name: https
          livenessProbe:
            exec:
              command:
                - pgrep
                - java
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
            successThreshold: 1
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP # Use pod ip
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name # Use pod name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace # Use pod namespace
            - name: NIFI_REGISTRY_UI_BANNER_TEXT
              value: $(POD_NAME) # Use pod name for banner
            - name: NIFI_REGISTRY_WEB_HTTPS_HOST
              value: $(POD_NAME).{{ .Chart.Name }}.$(POD_NAMESPACE).svc.cluster.local # Use pod fqdn as web host
            - name: NIFI_REGISTRY_CLUSTER_NODE_ADDRESS
              value: $(POD_NAME).{{ .Chart.Name }}.$(POD_NAMESPACE).svc.cluster.local # Use pod fqdn as node address
            - name: NIFI_REGISTRY_REMOTE_INPUT_SOCKET_HOST
              value: $(POD_NAME).{{ .Chart.Name }}.$(POD_NAMESPACE).svc.cluster.local # Use pod fqdn as input socket address
            - name: NIFI_REGISTRY_REMOTE_INPUT_HOST
              value: $(POD_NAME).{{ .Chart.Name }}.$(POD_NAMESPACE).svc.cluster.local # Use pod fqdn as input host address
            - name: HOSTNAME
              value: $(POD_IP) # Use pod ip as hostname
            - name: NODE_IDENTITY
              value: $(POD_NAME) # Use pod name as identity
            # << Vault >>>
            - name: NIFI_REGISTRY_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: nifireg-postgresql-pass
                  key: nifireg-postgresql-pass
            - name: KEYSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keystore-password
                  key: keystore-password
            - name: NIFI_REGISTRY_SECURITY_USER_OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: keystore-password
                  key: keystore-password
            - name: TRUSTSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: truststore-password
                  key: truststore-password
          # << / Vault >>
          envFrom:
            - configMapRef:
                name: "{{ .Chart.Name }}-cm"
                optional: false
          volumeMounts:
            ### NFS
            - name: nfs-pv-nifi-data
              mountPath: /opt/nifi-registry/nifi-registry-current/keytool
              subPath: keytool
              readOnly: false
            - name: nfs-pv-{{ .Chart.Name }}-data
              mountPath: /opt/nifi-registry/nifi-registry-current/extensions
              subPath: extensions
              readOnly: false
            - name: nfs-pv-{{ .Chart.Name }}-data
              mountPath: /opt/nifi-registry/nifi-registry-current/lib/postgresql-42.2.2.jar
              subPath: custom-libs/postgresql-42.2.2.jar
              readOnly: false
            - name: nfs-pv-{{ .Chart.Name }}-data
              mountPath: /opt/nifi-registry/nifi-registry-current/flow_storage
              subPath: flow_storage
              readOnly: false
            - name: nfs-pv-{{ .Chart.Name }}-data
              mountPath: /opt/nifi-registry/nifi-registry-current/volume_conf/authorizers.xml
              subPath: conf/authorizers.xml
              readOnly: false
            - name: nfs-pv-{{ .Chart.Name }}-data
              mountPath: /opt/nifi-registry/nifi-registry-current/volume_conf/identity-providers.xml
              subPath: conf/identity-providers.xml
              readOnly: false
            - name: nfs-pv-{{ .Chart.Name }}-data
              mountPath: /opt/nifi-registry/nifi-registry-current/volume_conf/providers.xml
              subPath: conf/providers.xml
              readOnly: false
            - name: nfs-pv-{{ .Chart.Name }}-data
              mountPath: /opt/nifi-registry/nifi-registry-current/volume_conf/registry-aliases.xml
              subPath: conf/registry-aliases.xml
              readOnly: false
            #Experemental
            - name: nfs-pv-{{ .Chart.Name }}-data
              mountPath: /opt/nifi-registry/nifi-registry-current/conf/authorizations.xml
              subPath: conf/authorizations.xml
              readOnly: false
            - name: nfs-pv-{{ .Chart.Name }}-data
              mountPath: /opt/nifi-registry/nifi-registry-current/conf/users.xml
              subPath: conf/users.xml
              readOnly: false
            # Доменный сертификат
            - name: cert-and-key
              mountPath: /etc/ssl/certs/keycloak.crt
              subPath: keycloak.crt
              readOnly: false
            - name: cert-and-key
              mountPath: /etc/ssl/certs/keycloak.key
              subPath: keycloak.key
              readOnly: false
            # Нужен для взаимодействия подов друг с другом
            - name: inside-cluster-ssl
              mountPath: /etc/ssl/certs/cluster.crt
              subPath: cluster.crt
              readOnly: false
            - name: inside-cluster-ssl
              mountPath: /etc/ssl/certs/cluster.key
              subPath: cluster.key
              readOnly: false
            - name: start-script
              mountPath: /opt/nifi-registry/scripts/start.sh
              subPath: start-nr.sh
              readOnly: false
            # << Vault >>>
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
            # <<- / Vault -->>
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            capabilities:
              drop:
                - ALL
      volumes:
        - name: nfs-pv-{{ .Chart.Name }}-data
          persistentVolumeClaim:
            claimName: nfs-pvc-{{ .Chart.Name }}-data
        - name: start-script
          configMap:
            name: start-nr.sh
            optional: false
            defaultMode: 0755
        - name: cert-and-key
          secret:
            secretName: "{{ .Chart.Name }}-cluster-secret"
            items:
              - key: tls.crt
                path: keycloak.crt
              - key: tls.key
                path: keycloak.key
                mode: 0600
        - name: inside-cluster-ssl
          secret:
            secretName: "{{ .Chart.Name }}-cluster-secret"
            items:
              - key: tls.crt
                path: cluster.crt
              - key: tls.key
                path: cluster.key
                mode: 0600
        # Будем смотреть в Truststore и Keystore NiFi
        - name: nfs-pv-nifi-data
          persistentVolumeClaim:
            claimName: nfs-pvc-nifi-data
            # << Vault >>>
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "vault-database-nifireg"
            # <<- / Vault -->>

