---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nifi-cm
data:
  DOMAIN: "cluster-k8s.ov.universe-data.ru"
  NIFI_SECURITY_USER_SAML_IDP_METADATA_URL: "https://cluster-k8s.ov.universe-data.ru/keycloak/auth/realms/master/protocol/saml/descriptor"
  K8S_NODES: "k8s-node3.ov.universe-data.ru,k8s-node2.ov.universe-data.ru,k8s-node1.ov.universe-data.ru"
  NIFI_JVM_TIMEZONE: "Europe/Moscow"
  KEYSTORE_PATH: /opt/nifi/nifi-current/keytool/all/keystore.jks
  TRUSTSTORE_PATH: /opt/nifi/nifi-current/keytool/all/truststore.jks
  NIFI_SECURITY_KEYSTORE: /opt/nifi/nifi-current/keytool/all/keystore.jks
  KEYSTORE_PASSWORD: "th1s1s3up34e5r37"
  TRUSTSTORE_PASSWORD: "th1s1s3up34e5r37"
  KEYSTORE_TYPE: "jks"
  TRUSTSTORE_TYPE: "JKS"
  NIFI_SECURITY_KEYSTORETYPE: "JKS"
  NIFI_ANALYTICS_PREDICT_ENABLED: "true"
  NIFI_CLUSTER_IS_NODE: "true"
  NIFI_CLUSTER_LOAD_BALANCE_HOST: "nifi"
  NIFI_CLUSTER_NODE_CONNECTION_TIMEOUT: "5 min"
  NIFI_CLUSTER_NODE_READ_TIMEOUT: "1 min"
  NIFI_CLUSTER_NODE_EVENT_HISTORY_SIZE: "25"
  NIFI_CLUSTER_NODE_LOAD_BALANCE_PORT: "6342"
  NIFI_CLUSTER_NODE_PROTOCOL_MAX_THREADS: "20"
  NIFI_CLUSTER_NODE_PROTOCOL_PORT: "11443"
  NIFI_CLUSTER_NODE_PROTOCOL_THREADS: "10"
  NIFI_CLUSTER_PROTOCOL_CONNECTION_HANDSHAKE_TIMEOUT: "3 min"
  NIFI_CLUSTER_PROTOCOL_HEARTBEAT_INTERVAL: "2 min"
  NIFI_CLUSTER_PROTOCOL_IS_SECURE: "true"
  NIFI_ELECTION_MAX_CANDIDATES: "3" # равно количеству участников кластера
  NIFI_ELECTION_MAX_WAIT: "2 min"
  NIFI_JVM_HEAP_INIT: "2g"
  NIFI_JVM_HEAP_MAX: "6g"
  NIFI_SECURITY_AUTORELOAD_ENABLED: "true"
  NIFI_SECURITY_AUTORELOAD_INTERVAL: "5 min"
  NIFI_SECURITY_NEEDCLIENTAUTH: "true"
  NIFI_CONTENT_CLAIM_MAX_APPENDABLE_SIZE: "1 MB"
  AUTH: "saml"
  NIFI_SECURITY_USER_SAML_SP_ENTITY_ID: org:apache:nifi:saml:all
  NIFI_SECURITY_USER_SAML_GROUP_ATTRIBUTE_NAME: "member"
  NIFI_SECURITY_USER_SAML_REQUEST_SIGNING_ENABLED: "false"
  NIFI_SECURITY_USER_SAML_WANT_ASSERTIONS_SIGNED: "true"
  NIFI_SECURITY_USER_SAML_SIGNATURE_ALGORITHM: "http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"
  NIFI_SECURITY_USER_SAML_SIGNATURE_DIGEST_ALGORITHM: "http://www.w3.org/2001/04/xmlenc#sha256"
  NIFI_SECURITY_USER_SAML_MESSAGE_LOGGING_ENABLED: "false"
  NIFI_SECURITY_USER_SAML_METADATA_SIGNING_ENABLED: "false"
  NIFI_SECURITY_USER_SAML_AUTHENTICATION_EXPIRATION: "12 hours"
  NIFI_SECURITY_USER_SAML_SINGLE_LOGOUT_ENABLED: "true"
  NIFI_SECURITY_USER_SAML_HTTP_CLIENT_TRUSTSTORE_STRATEGY: "NIFI"
  NIFI_SECURITY_USER_SAML_HTTP_CLIENT_CONNECT_TIMEOUT: "30 secs"
  NIFI_SECURITY_USER_SAML_HTTP_CLIENT_READ_TIMEOUT: "30 secs"
  NIFI_SERVICE_CLIENT_SECRET: "DQ7CF7OX2LIxl8VF7WQTdlH4PIoM1czQ"
  INITIAL_ADMIN_IDENTITY: "admin"
  NIFI_SENSITIVE_PROPS_KEY_PROTECTED: "th1s1s3up34e5r37"
  NIFI_SENSITIVE_PROPS_KEY: "th1s1s3up34e5r37"
  NIFI_WEB_HTTPS_PORT: "8443"
  NIFI_WEB_PROXY_HOST: "cluster-k8s.ov.universe-data.ru"
  NIFI_ZK_CONNECT_STRING: "zookeeper:2181"
  NIFI_ZOOKEEPER_CONNECT_STRING: "zookeeper:2181"
