---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  app.kubernetes.io/managed-by: kustomization

resources:
  - ingress.yml
  - configmap.yml
  - start-configmap.yml
  - nifi-registry.yml
  - hpa.yml
  - secrets.yml
  - nifi-registry-cluster-secret.yml
  - service.yml

images:
  - name: nifi-registry
    newName: docker.io/apache/nifi-registry
    newTag: "1.24.0"
  - name: wait
    newName: docker.io/busybox
    newTag: "1.36"
